# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: /data/robotic/data_reduce_valid_crop/val_data_joint.npy
  label_path: /data/robotic/data_reduce_valid_crop/val_label.pkl
  debug: False

# model
model: model.msg3d.Model
model_args:
  # original classes
  #  num_class: 55
  #reduced classes
  num_class: 37
  num_point: 17
  num_person: 1
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

# test
phase: test
device: [0,1]
test_batch_size: 32
#weights: ./work_dir/data_reduce_valid/weights/weights-44-224708.pt
weights: ./work_dir/robot_reduce_valid_crop/weights/weights-7-10003.pt

save_score: True