# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/robot/X_global_data.npy
  label_path: ./data/robot/Y_global_data.json
  debug: True

# model
model: model.msg3d.Model
model_args:
  num_class: 55
  num_point: 17
  num_person: 1
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

# test
phase: test
device: [0]
test_batch_size: 2
weights: ./work_dir/weights/weights-1-25.pt
#weights: ./pretrained_models/ntu120_xsub_joint.pt

work_dir: ./eval/robot/
save_score: True