work_dir: ./work_dir/robot/data_reduce_valid_crop

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
#  data_path: /data/robotic/train_data_joint.npy
#  label_path: /data/robotic/train_label.pkl

#  data_path: /data/robotic/data_reduce_valid/train_data_joint.npy
#  label_path: /data/robotic/data_reduce_valid/train_label.pkl

  data_path: /data/robotic/data_reduce_valid_crop/train_data_joint.npy
  label_path: /data/robotic/data_reduce_valid_crop/train_label.pkl

  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
#  data_path: /data/robotic/val_data_joint.npy
#  label_path: /data/robotic/val_label.pkl

#  data_path: /data/robotic/data_reduce_valid/val_data_joint.npy
#  label_path: /data/robotic/data_reduce_valid/val_label.pkl

#  data_path: /data/robotic/data_reduce_valid_crop/val_data_joint.npy
#  label_path: /data/robotic/data_reduce_valid_crop/val_label.pkl

  data_path: /data/robotic/data_reduce_valid_crop/val_data_joint.npy
  label_path: /data/robotic/data_reduce_valid_crop/val_label.pkl

  debug: False

# model
model: model.msg3d.Model
model_args:
  # original classes
#  num_class: 55
  #reduced classes
  num_class: 37
  num_point: 17
  num_person: 1
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

# optim
weight_decay: 0.0005
base_lr: 0.05
step: [30, 40]

# training
num_epoch: 100
device: [0,1]
batch_size: 32
forward_batch_size: 32
test_batch_size: 32
nesterov: True