
work_dir: ./work_dir/ntu/xsub/msg3d_joint

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
#  data_path: ./data/ntu/xsub/train_data_joint.npy
#  label_path: ./data/ntu/xsub/train_label.pkl

#  data_path: ./data/robot/X_global_data.npy
#  label_path: ./data/robot/Y_global_data.json

#  data_path: ./data/robot/X_format_NCTV.npy
  data_path: ./data/robot/X_format_NCTVM.npy
  label_path: ./data/robot/Y_global_data.json

  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
#  data_path: ./data/ntu/xsub/val_data_joint.npy
#  label_path: ./data/ntu/xsub/val_label.pkl

#  data_path: ./data/robot/X_format_NCTV.npy
  data_path: ./data/robot/X_format_NCTVM.npy
  label_path: ./data/robot/Y_global_data.json

#  data_path: ./data/robot/X_global_data.npy
#  label_path: ./data/robot/Y_global_data.json

# model
model: model.msg3d.Model
model_args:
  num_class: 60
  num_point: 17
  num_person: 1
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

# optim
weight_decay: 0.0005
base_lr: 0.05
step: [30, 40]

# training
num_epoch: 50
device: [0]
batch_size: 2
forward_batch_size: 2
test_batch_size: 2
nesterov: True

