work_dir: ./eval/kinetics/joint/

# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
#  data_path: ./data/kinetics/val_data_joint.npy
#  label_path: ./data/kinetics/val_label.pkl
  data_path: /media/hao/My Passport/dataset/shopping_mall_robotic/val_data_joint_light.npy
  label_path: /media/hao/My Passport/dataset/shopping_mall_robotic/val_label_light.pkl
  debug: False

# model
model: model.msg3d.Model
model_args:
  num_class: 55
  num_point: 17
  num_person: 1
  num_gcn_scales: 8
  num_g3d_scales: 8
  graph: graph.kinetics.AdjMatrixGraph


# test
phase: test
device: 0
test_batch_size: 1
weights: ./pretrained_models/kinetics-joint.pt
save_score: True