# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
#  data_path: /media/hao/My Passport/dataset/shopping_mall_robotic/robot_reduce_valid_crop/val_data_joint_light.npy
#  label_path: /media/hao/My Passport/dataset/shopping_mall_robotic/robot_reduce_valid_crop/val_label_light.pkl

#  data_path: /media/hao/My Passport/dataset/robot/output/val_data_joint.npy
#  label_path: /media/hao/My Passport/dataset/robot/output/val_label.pkl

  data_path: /media/hao/My Passport/dataset/robot/output_debug/val_data_joint_light.npy
  label_path: /media/hao/My Passport/dataset/robot/output_debug/val_label_light.pkl

#  data_path: /media/hao/My Passport/dataset/itw-s/backup/val_data_joint_light.npy
#  label_path: /media/hao/My Passport/dataset/itw-s/backup/val_label_light.pkl

  debug: False

# model
model: model.msg3d.Model
model_args:
#  num_class: 55
  num_class: 37
  num_point: 17
  num_person: 1
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

# test
phase: test
device: [0]
test_batch_size: 2
#weights: pretrained_models/weights-MSG3D_standard-342169.pt
weights: ./pretrained_models/weights-67-342169.pt

save_score: False